import { writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";
import { cssVarName, values } from "../src/styles/tokens";

const HEADER = "Generated by `bun run generate`. Do not edit.";

const CONTRACTS = ["user-service", "supplier-service"];

function tokensCss(): string {
  const lines = Object.entries(values).flatMap(([group, scale]) =>
    Object.entries(scale).map(([key, value]) => `  ${cssVarName(group, key)}: ${value};`),
  );
  return `/* ${HEADER} Edit tokens.ts. */\n:root {\n${lines.join("\n")}\n}\n`;
}

async function contractTypes(name: string): Promise<string> {
  const contract = new URL(`../../contracts/${name}.openapi.yaml`, import.meta.url);
  return `// ${HEADER} Source: contracts/${name}.openapi.yaml\n\n${astToString(await openapiTS(contract))}`;
}

/** Every generated file, keyed by its path from the web-app root. */
export async function generatedFiles(): Promise<Record<string, string>> {
  const files: Record<string, string> = { "src/styles/tokens.css": tokensCss() };
  for (const name of CONTRACTS) files[`src/lib/generated/${name}.ts`] = await contractTypes(name);
  return files;
}

if (import.meta.main) {
  for (const [path, content] of Object.entries(await generatedFiles())) {
    await writeFile(new URL(`../${path}`, import.meta.url), content);
    console.log(`wrote ${path}`);
  }
}
