import type { ErrandRequest, LedgerEntry, Supplier } from "./types";

// Fixed reference point (not Date.now()) so seed timestamps are identical
// on the server-rendered HTML and the client hydration pass.
const SEED_NOW = new Date("2026-09-15T09:30:00Z").getTime();

export const INITIAL_REQUESTS: ErrandRequest[] = [
  {
    id: "r1",
    title: "Deliver UTown Luckin Order #123 to PGP",
    supplier: "Luckin Coffee @ UTown",
    dropoff: "PGP Foyer",
    description: "Order number #123 from Luckin",
    credits: 12,
    status: "open",
    requesterId: "u-wei-jie",
    requesterName: "Wei Jie Tan",
    expiryLabel: "Expires in 24 min",
    createdAt: SEED_NOW - 1000 * 60 * 6,
  },
  {
    id: "r2",
    title: "Collect print job from PC Commons",
    supplier: "Printers @ PC Commons",
    dropoff: "COM1 Level 2",
    description: "Black & white, 12 pages, name Priya",
    credits: 8,
    status: "open",
    requesterId: "u-priya",
    requesterName: "Priya Nair",
    expiryLabel: "Expires in 41 min",
    createdAt: SEED_NOW - 1000 * 60 * 4,
  },
  {
    id: "r3",
    title: "FairPrice run to PGP House 7",
    supplier: "FairPrice @ UTown",
    dropoff: "PGP House 7",
    description: "Milk, eggs, and instant noodles — receipt will be reimbursed",
    credits: 15,
    status: "open",
    requesterId: "u-marcus",
    requesterName: "Marcus Lim",
    expiryLabel: "Expires in 12 min",
    createdAt: SEED_NOW - 1000 * 60 * 9,
  },
  {
    id: "r4",
    title: "Deck Koufu lunch to AS6",
    supplier: "Deck Koufu",
    dropoff: "AS6 Level 3",
    description: "Chicken rice, no cucumber",
    credits: 10,
    status: "open",
    requesterId: "u-sofia",
    requesterName: "Sofia Rahman",
    expiryLabel: "Expires in 33 min",
    createdAt: SEED_NOW - 1000 * 60 * 2,
  },
  {
    id: "r5",
    title: "Pickup my order please",
    supplier: "Luckin Coffee UTown",
    dropoff: "PGPR",
    description: "Order number #67 from Luckin",
    credits: 12,
    status: "open",
    requesterId: "me",
    requesterName: "You",
    expiryLabel: "Expires in 28 min",
    createdAt: SEED_NOW - 1000 * 60 * 3,
  },
  {
    id: "r5b",
    title: "Grab my parcel from UTown mailroom",
    supplier: "UTown Mailroom",
    dropoff: "Eusoff Hall",
    description: "Parcel under 'Anselm', locker slip in my mailbox",
    credits: 18,
    status: "open",
    requesterId: "me",
    requesterName: "You",
    expiryLabel: "Expires in 50 min",
    createdAt: SEED_NOW - 1000 * 60 * 1,
  },
  {
    id: "r6",
    title: "Deliver UTown Luckin Order #123 to PGP",
    supplier: "Luckin Coffee @ UTown",
    dropoff: "PGP Foyer",
    description: "Order number #59 from Luckin",
    credits: 12,
    status: "complete",
    requesterId: "me",
    requesterName: "You",
    expiryLabel: "Completed yesterday",
    createdAt: SEED_NOW - 1000 * 60 * 60 * 26,
  },
  {
    id: "r7",
    title: "Deliver UTown Luckin Order #123 to PGP",
    supplier: "Luckin Coffee @ UTown",
    dropoff: "PGP Foyer",
    description: "Order number #41 from Luckin",
    credits: 12,
    status: "cancelled",
    requesterId: "me",
    requesterName: "You",
    expiryLabel: "Cancelled last week",
    createdAt: SEED_NOW - 1000 * 60 * 60 * 24 * 7,
  },
];

export const INITIAL_LEDGER: LedgerEntry[] = [
  {
    id: "l1",
    type: "earned",
    label: "Errand completed",
    detail: "FairPrice run to PGP",
    amount: 15,
    createdAt: SEED_NOW - 1000 * 60 * 60 * 3,
  },
  {
    id: "l2",
    type: "released",
    label: "Credits released",
    detail: "Request expired unaccepted",
    amount: 8,
    createdAt: SEED_NOW - 1000 * 60 * 60 * 5,
  },
  {
    id: "l3",
    type: "spent",
    label: "Errand paid",
    detail: "Coffee run from COM3",
    amount: -12,
    createdAt: SEED_NOW - 1000 * 60 * 60 * 20,
  },
  {
    id: "l4",
    type: "reserved",
    label: "Credits reserved",
    detail: "Print job from PC Commons",
    amount: -8,
    createdAt: SEED_NOW - 1000 * 60 * 60 * 22,
  },
  {
    id: "l5",
    type: "earned",
    label: "Errand completed",
    detail: "Luckin order delivered to PGP",
    amount: 12,
    createdAt: SEED_NOW - 1000 * 60 * 60 * 26,
  },
];

export const SUPPLIERS: Supplier[] = [
  { id: "s1", name: "CoffeeBean @ COM3", location: "COM3, Level 1", category: "Café", distance: "4 min" },
  { id: "s2", name: "Printers @ PC Commons", location: "COM1, Level 1", category: "Printers", distance: "6 min" },
  { id: "s3", name: "Luckin Coffee @ UTown", location: "Stephen Riady Centre", category: "Café", distance: "11 min" },
  { id: "s4", name: "FairPrice @ UTown", location: "UTown Square, B1", category: "Marts", distance: "12 min" },
  { id: "s5", name: "PGP Foyer", location: "Prince George's Park", category: "Landmark", distance: "2 min" },
  { id: "s6", name: "Deck Koufu", location: "AS8, Level 1", category: "Canteen", distance: "8 min" },
];

export const INITIAL_BALANCE = 120;
export const INITIAL_RESERVED = 30;
